In [2]:
Задание 1
Создайте numpy array с элементами от числа N до 0 
 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [31]:
import numpy as np
N=10
np.arange(N-1, -1, -1)


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
np.diag(np.arange(N-1, -1, -1), k=0)

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.diag(np.arange(N-1, -1, -1), k=0).sum()

45

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [22]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [23]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [25]:
Задание 4
Имеется матрица покупок в интернет-магазине: users_stats 
На сайт заходит очередной посетитель, о покупках которого известно следующее: next_user_stats 
Найдите из числа покупателей users_stats самого похожего на next_user_stats

In [45]:
users_stats = np.array([
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], np.int32)

next_user_stats = np.array([0, 1, 2, 0, 0, 0], np.int32)

def cosine( a, b ):
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    return np.dot ( a, b ) / ( aLength * bLength )

l = []
m = 0

for line in users_stats:
    if cosine( line, next_user_stats ) > m:
        m = cosine( line, next_user_stats )
        l = line   
        
print ('Больше всего похож на next_user_stats Покупатель, сделавший покупки: ', l)
print ('Максимальное значение косинуса = ', m)
print ('Минимальный угол = ', np.arccos(m) * 360 / 2 / np.pi, ' градусов')

Больше всего похож на next_user_stats Покупатель, сделавший покупки:  [0 1 1 0 0 0]
Максимальное значение косинуса =  0.9486832980505138
Минимальный угол =  18.434948822922017  градусов
